org: ddavies90
app: tonight-express-api
service: tonight-express-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: eu-west-2
  httpApi:
    cors:
      allowedMethods:
        - GET

functions:
  api:
    handler: api.api
    events:
    - httpApi:
        path: /{city}
        method: get

custom:
  tableName: tonight-users

resources:
  Resources:
    myDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: UID
            AttributeType: S
          - AttributeName: ActID
            AttributeType: S
        KeySchema:
          - AttributeName: UID
            KeyType: HASH
          - AttributeName: ActID
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
